const insuredes = {

    namespaced : true,

    state : {
        insuredesDetails : [
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : false,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : false,
            },
            {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : false,
            },
                       {
                collective : 'שם קולקטיב',
                branch : 'רכב',
                product : 'שם המוצר' ,
                insuredName : 'יצחק אברהם',
                licenseNumber : '12-345-67',
                id : '039894872',
                openingOffer : '12.10.2019',
                beginningInsurance : '04.04.2020',
                policyNumber : '123456789012',
                sentToCustomer : true,
            },
            
        ]
    },

    getters : {
        getInsuredesDetails : state => {
            return state.insuredesDetails
        }
    },

}

export default insuredes;